### ISSUE TITLE
Preparation for Shlink Dashboard

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink-web-client#338]
Shlink web client is a fully static web app, with no backend.

That's pretty convenient, and simplifies a lot of things, but also introduces some limitations.

* Servers and configuration is not shared, which means every time you open the app in a new device, you need to configure it from scratch.
* Everything is public, so you cannot set permissions or user authentication.
* Shlink API keys are stored in the browser, which is a bit risky if someone else can access your computer.
* Many people don't understand the difference of a web app with backend and without it, which makes them not understand why the former points are not possible.

Since there has been requests for this in the past, I'm considering a new shlink-dashboard project, which would be a web client but with its own backend for frontend.

In order to do it, we need to split shlink-web-client, having a subcomponent which wraps all the operations done when you are connected to a server.

This component would be reused by both shlink-web-client and shlink-dashboard, and the list of servers, configs, etc, would be handled differently by each one of them.

It should aslo allow (at some point) to provide the list of permissions, so that shlink-dashboard can "hide" sections based on the user's permissions.

Once the component has been split (shlink-web-component?), it can be moved to its own repo and published separately as an npm package.

---

### TODO

- [x] Split redux store
  - APP:
    - appUpdates
    - servers (remoteServers, selectedServer)
    - settings
    - sidebar
  - COMPONENT:
    - Everything else
- [x] Split container definition
- [x] Identify common components between this component and the wrapping app
  - [x] `Result`
  - [x] `Message`
  - [x] `SimpleCard`
  - [x] `SearchField`
  - [x] `DropdownBtn`
  - [x] `RowDropdownBtn`
  - [x] `InputFormGroup`
  - [x] `Checkbox`, `ToggleSwitch` and `BooleanControl`
  - [x] `NavPills` and `NavPillItem`
  - [x] `OrderingDropdown` and order helpers.
  - [x] hooks:
    - `useDomId`
    - `useElementRef`
    - `useToggle`
- [x] Define the API client contract
- [x] Think how to use mercure: 
  - Let component subscribe.
  - ~Pass updates from app~
- [x] Define what/how to export from component package
- [x] Make sure shlink-web-component does not have dependencies on the app
- [x] Consider how to split/bundle stylesheets
  - Compile pure styles and distribute an index.css file. Import them once.
  ```scss
  @import '@shlinkio/shlink-frontend-kit/index';
  @import '@shlinkio/shlink-web-component/index';
  ```
  - Expose mixins and vars on a `base.scss` which is distributed uncompiled and then imported wherever needed.
  ```scss
  @import '@shlinkio/shlink-frontend-kit/base';  
  ```
- [x] Extract individual stylesheets which are used only by shlink-web-component
- [x] Try to get rid of sidebar reducer.
- [x] Move short-urls/data into api-contract
- [x] Dynamically wrap on a Router instance if not already wrapped.
- [x] Review where styles are defined, and move them to the right stylesheet if needed.

### Extracted component

Potential component names:
- `<Shlink />`
- `<ShlinkWebComponent />`
- `<ShlinkWeb />`
- `<ShlinkClient />`
- `<ShlinkApp />`

Usage:

```tsx
import { ShlinkWebComponent } from '@shlinkio/shlink-web-component';
import type { Settings } from '@shlinkio/shlink-web-component';
import type { ShlinkApiClient } from '@shlinkio/shlink-web-component/api-contract';

<ShlinkWebComponent
  settings={{} as Settings} // The settings (from local storage or server)
  serverVersion="3.7.0" // To resolve supported features.
  apiClient={{} as ShlinkApiClient} // An API client / an object fulfilling a contract. Implicitly knows how to consume current server

  // Object determining the active section and its params, or use react-router?
  activeSection={{}}

  // Future versions
  permissions={{}} // Allows to hide sections or restrict actions
/>
```

Peer dependencies:
- @reduxjs/toolkit (redux?)
- react-redux
- react
- react-dom
- bootstrap
- reactstrap
- date-fns

**Comment by garethjax** [comment]
Hi @acelaya, it's great! would then be possible to export the chart data?

**Comment by acelaya** [comment]
Hey @garethjax.

That's something I have considered many times. Could you please open a separate feature request ticket for that?

**Comment by garethjax** [comment]
of course!

**Comment by wfjsw** [comment]
Some thoughts:

 - We can still store the frontend settings as a tiny JSON snippet to one of the configured backend servers and allow web-client to load/save/sync with it while authed. As a bare minimum solution GitHub Gists API supports CORS and we can save our settings there.
 - It doesn't matter that the routes and views in web-client are public and it doesn't prevent us from setting up access restrictions to backend routes then provide the token information for web-client to hide a few links. Why bother making the pages public while impossible to retrieve any data?
 - I'd rather argue that the API key itself is not secure. It probably subjects to brute-force attack since there isn't any rate limit on error tokens and rotating existing ones requires human effort but storing them into local storage is generally fine as long as we don't create easy XSS vulnerabilities. if being skeptical, there is an alternative approach that requires web-client to retrieve a HTTP-only session cookie with the given API key and store that cookie instead (the browser does that for you). The cookie is relatively easy to rotate and in that way we only need to take care of CSRF attacks (only requests that changes something need it) and it's all good.

**Comment by acelaya** [comment]
>  We can still store the frontend settings as a tiny JSON snippet to one of the configured backend servers and allow web-client to load/save/sync with it while authed. As a bare minimum solution GitHub Gists API supports CORS and we can save our settings there.

I tried supporting sync with a private filesystem (Dropbox, Google Drive, etc). It was a nightmare and had to discard it, haha.

Databases have their own locking mechanisms, which would simplify it.

I haven't tried other options though. I'll give it a thought.

>  It doesn't matter that the routes and views in web-client are public and it doesn't prevent us from setting up access restrictions to backend routes then provide the token information for web-client to hide a few links. Why bother worrying as it is impossible to retrieve any data?

The problem with shlink-web-client is that it's all public right now, it doesn't have backend at all, which means you have to "leak" the API key to the browser, which can later be used by any person to bypass the UI completely.

There are organizations that want to have their Shlink instance non-public, and provide different credentials to different people. Some will be able to create short URLs, but not delete them, some will only have read access to stats so that they can generate analytics, etc.

With something like shlink-dashboard, you can achieve that, as users never have access to the API key, just their credentials for the dashboard itself (requests to Shlink API would happen from the dashboard's backend, not from the browser, as it happens in shlink-web-client).

>  I'd rather argue that the API key itself is not secure. It probably subjects to brute-force attack since there isn't any rate limit on error tokens and rotating existing ones requires human effort but storing them into local storage is generally fine as long as we don't create easy XSS vulnerabilities.

Yes, you are right here, and that's why shlink-web-client is working like that at the moment.

However, there are companies with more strict security constraints that do not consider this secure enough. Shlink-dashboard would provide that extra security for those that need it.

> if being skeptical, there is an alternative approach that requires web-client to retrieve a HTTP-only session cookie with the given API key and store that cookie instead (the browser does that for you). The cookie is relatively easy to rotate and in that way we only need to take care of CSRF attacks (only requests that changes something need it) and it's all good.

Well, that's precisely what I want to do with shlink-dashboard. As I said, skink-web-client does not have a backend of it's own that can handle the cookies. That's the whole point.

**Comment by wfjsw** [comment]
> I tried supporting sync with a private filesystem (Dropbox, Google Drive, etc). It was a nightmare and had to discard it, haha.
> 
> Databases have their own locking mechanisms, which would simplify it.
> 
> I haven't tried other options though. I'll give it a thought.

Can you please elaborate? It sounds frustrating to me as it indicates that the settings are changing so frequent that requires a complex protocol to lock and sync. So far I can live with last modified timestamp and as long as it won't wander off to an invalid state then it's fine.

> The problem with shlink-web-client is that it's all public right now, it doesn't have backend at all, which means you have to "leak" the API key to the browser, which can later be used by any person to bypass the UI completely.
> 
> There are organizations that want to have their Shlink instance non-public, and provide different credentials to different people. Some will be able to create short URLs, but not delete them, some will only have read access to stats so that they can generate analytics, etc.
> 
> With something like shlink-dashboard, you can achieve that, as users never have access to the API key, just their credentials for the dashboard itself (requests to Shlink API would happen from the dashboard's backend, not from the browser, as it happens in shlink-web-client).

I smells danger that we are trying to do access control entirely on frontend side. For a project designed as such, it is safe to just assume that the frontend does not exist and everyone is using REST API to directly talk to server. The web-client is just a tool to help to craft such request thus should not be considered at all in authentications.

different credentials === different API keys. Why not? We only need an extensive permission system instead of a fresh project for everything to work. Revoke the ability to delete short url etc. via REST API and we are good to go.

> Well, that's precisely what I want to do with shlink-dashboard. As I said, shlink-web-client does not have a backend of it's own that can handle the cookies. That's the whole point.

Check this out: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials
https://discourse.mozilla.org/t/fetch-will-not-accept-cross-site-foreign-cookies/48616/7
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#differences_from_jquery

TL;DR: You can utilize cross-origin cookies in the same way as the regular one as long as
 - [`credentials: include`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials#examples)
 - [`SameSite=None; Secure` ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#none); favorably `HttpOnly`
 - `Access-Control-Allow-Origin: anything but *` we can read the `Origin` header from request header and change accordingly
 - `Access-Control-Allow-Headers: Cookie` 

The major non-issue here is we cannot read the cookie value into web-client context but it still allows us to authenticate with it. 

Then there is CSRF issue. We may force a CSRF token (Transmission way) or we can exploit the `Origin` header and add an extra option to specify allowed origins in the shlink server. We can examine the `User-Agent` and only apply such restrictions to browser.

**Comment by acelaya** [comment]
All preparations are done.

**Comment by mvalois** [comment]
Hey, we're interested by this project!
Is there any ETA for the Shlink Dashboard?
Any way to help? Any todo list?

**Comment by mredodos** [comment]
Hi some news about that?

**Comment by acelaya** [comment]
For those subscribed to this issue, just letting you know Shlink Dashboard has just been released https://github.com/shlinkio/shlink-dashboard
